const fs = require("fs");
const path = require("path");

const projectName = "universal-guard-production";
const root = path.resolve(process.cwd(), projectName);

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function write(rel, content) {
  const file = path.join(root, rel);
  ensureDir(path.dirname(file));
  fs.writeFileSync(file, content, "utf8");
}

function rmrf(target) {
  fs.rmSync(target, { recursive: true, force: true });
}

rmrf(root);
ensureDir(root);

const files = {
  "package.json": `{
  "name": "universal-guard-production",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "prisma generate && next build",
    "start": "next start",
    "db:push": "prisma db push",
    "db:seed": "node prisma/seed.cjs",
    "studio": "prisma studio"
  },
  "dependencies": {
    "@paypal/react-paypal-js": "^8.8.3",
    "@prisma/client": "^5.22.0",
    "bcryptjs": "^2.4.3",
    "jose": "^5.9.6",
    "lucide-react": "^0.468.0",
    "next": "^15.1.6",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "zod": "^3.24.1"
  },
  "devDependencies": {
    "@types/bcryptjs": "^2.4.6",
    "@types/node": "^22.10.2",
    "@types/react": "^19.0.2",
    "@types/react-dom": "^19.0.2",
    "autoprefixer": "^10.4.20",
    "postcss": "^8.4.49",
    "prisma": "^5.22.0",
    "tailwindcss": "^3.4.17",
    "typescript": "^5.7.2"
  }
}
`,

  ".env.example": `NEXT_PUBLIC_APP_NAME="Universal Guard"
AUTH_SECRET="replace_with_a_long_random_secret_at_least_32_chars"

DATABASE_URL="postgresql://user:password@localhost:5432/universal_guard?schema=public"

PAYPAL_ENV="sandbox"
PAYPAL_CLIENT_ID="your_paypal_client_id"
PAYPAL_CLIENT_SECRET="your_paypal_client_secret"
PAYPAL_WEBHOOK_ID="your_paypal_webhook_id"
NEXT_PUBLIC_PAYPAL_CLIENT_ID="your_paypal_client_id"

LICENSE_PRODUCT_ID="UG-PROD-001"
LICENSE_DURATION_DAYS="365"
LICENSE_PRICE_USD="49.00"
`,

  "README.md": `# Universal Guard Production

## Setup

1. Install dependencies:

\`\`\`bash
npm install
\`\`\`

2. Copy environment file:

\`\`\`bash
copy .env.example .env.local
\`\`\`

3. Edit \`.env.local\` and set your database and PayPal values.

4. Push database schema:

\`\`\`bash
npx prisma db push
\`\`\`

5. Seed default admin:

\`\`\`bash
npm run db:seed
\`\`\`

6. Start development server:

\`\`\`bash
npm run dev
\`\`\`

## Default login

Username:

\`\`\`text
admin
\`\`\`

Password:

\`\`\`text
admin123
\`\`\`

Change this immediately in production.
`,

  "next.config.js": `/** @type {import('next').NextConfig} */
const nextConfig = {
  output: "standalone"
};

module.exports = nextConfig;
`,

  "postcss.config.js": `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {}
  }
};
`,

  "tailwind.config.ts": `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}"
  ],
  theme: {
    extend: {}
  },
  plugins: []
};

export default config;
`,

  "tsconfig.json": `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "es2022"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
`,

  "next-env.d.ts": `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is automatically generated by Next.js.
`,

  "prisma/schema.prisma": `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model AdminUser {
  id           Int      @id @default(autoincrement())
  username     String   @unique
  passwordHash String
  role         String   @default("owner")
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
}

model Player {
  id            Int       @id @default(autoincrement())
  accountName   String    @unique
  characterName String
  level         Int       @default(1)
  gold          BigInt    @default(0)
  ipAddress     String?
  status        String    @default("active")
  notes         String?
  lastLoginAt   DateTime?
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
}

model License {
  id          Int       @id @default(autoincrement())
  productId   String
  licenseKey  String    @unique
  ownerEmail  String?
  status      String    @default("inactive")
  activatedAt DateTime?
  expiresAt   DateTime?
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @updatedAt
  orderId     String?   @unique
  payerId     String?
  notes       String?
}

model AuditLog {
  id        Int      @id @default(autoincrement())
  actor     String
  action    String
  entity    String
  entityId  String?
  metadata  Json?
  createdAt DateTime @default(now())
}
`,

  "prisma/seed.cjs": `const { PrismaClient } = require("@prisma/client");
const bcrypt = require("bcryptjs");

const prisma = new PrismaClient();

async function main() {
  const passwordHash = bcrypt.hashSync("admin123", 12);

  await prisma.adminUser.upsert({
    where: { username: "admin" },
    update: { passwordHash, role: "owner" },
    create: {
      username: "admin",
      passwordHash,
      role: "owner"
    }
  });

  await prisma.player.upsert({
    where: { accountName: "account001" },
    update: {},
    create: {
      accountName: "account001",
      characterName: "RogueBlade",
      level: 110,
      gold: 945000000n,
      ipAddress: "185.22.10.4",
      status: "active",
      notes: "Trusted player"
    }
  });

  await prisma.player.upsert({
    where: { accountName: "account002" },
    update: {},
    create: {
      accountName: "account002",
      characterName: "MoonWizard",
      level: 98,
      gold: 120000000n,
      ipAddress: "185.22.10.5",
      status: "active"
    }
  });

  await prisma.player.upsert({
    where: { accountName: "account003" },
    update: {},
    create: {
      accountName: "account003",
      characterName: "GoldTrader",
      level: 80,
      gold: 2500000000n,
      ipAddress: "91.10.45.8",
      status: "flagged",
      notes: "High gold movement"
    }
  });

  console.log("Seed complete.");
  console.log("Login: admin / admin123");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
`,

  "app/globals.css": `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --bg: #050816;
  --bg2: #0a1023;
  --panel: rgba(15, 23, 42, 0.78);
  --border: rgba(148, 163, 184, 0.18);
  --text: #e5e7eb;
  --muted: #94a3b8;
}

html,
body {
  min-height: 100%;
  background:
    radial-gradient(circle at top left, rgba(96,165,250,0.17), transparent 28%),
    radial-gradient(circle at top right, rgba(167,139,250,0.14), transparent 24%),
    linear-gradient(180deg, var(--bg), var(--bg2));
  color: var(--text);
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
}

a {
  color: inherit;
  text-decoration: none;
}

.panel {
  background: linear-gradient(180deg, rgba(255,255,255,0.07), rgba(255,255,255,0.025));
  border: 1px solid var(--border);
  border-radius: 18px;
  backdrop-filter: blur(14px);
  box-shadow: 0 24px 80px rgba(0,0,0,0.22);
}

.input {
  width: 100%;
  padding: 0.85rem 1rem;
  border-radius: 14px;
  background: rgba(2, 6, 23, 0.55);
  border: 1px solid rgba(148, 163, 184, 0.24);
  color: var(--text);
  outline: none;
}

.input:focus {
  border-color: rgba(96,165,250,0.75);
  box-shadow: 0 0 0 4px rgba(96,165,250,0.15);
}

.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.45rem;
  padding: 0.8rem 1rem;
  border-radius: 14px;
  border: 1px solid rgba(148, 163, 184, 0.2);
  cursor: pointer;
  transition: 150ms ease;
}

.btn:hover {
  transform: translateY(-1px);
}

.btn-primary {
  background: linear-gradient(135deg, #2563eb, #7c3aed);
  color: white;
}

.btn-secondary {
  background: rgba(255,255,255,0.06);
  color: var(--text);
}

.badge {
  display: inline-flex;
  align-items: center;
  padding: 0.2rem 0.55rem;
  border-radius: 999px;
  border: 1px solid rgba(148,163,184,0.22);
  background: rgba(255,255,255,0.05);
  font-size: 0.75rem;
}

.table {
  width: 100%;
  border-collapse: collapse;
}

.table th,
.table td {
  border-bottom: 1px solid rgba(148,163,184,0.15);
  padding: 0.8rem;
  text-align: left;
}

.table th {
  color: #94a3b8;
  font-size: 0.8rem;
  font-weight: 600;
}
`,

  "app/layout.tsx": `import "./globals.css";

export const metadata = {
  title: "Universal Guard",
  description: "Production-ready license and admin platform"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,

  "app/page.tsx": `import { redirect } from "next/navigation";

export default function HomePage() {
  redirect("/login");
}
`,

  "lib/prisma.ts": `import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as {
  prisma?: PrismaClient;
};

export const prisma =
  globalForPrisma.prisma ||
  new PrismaClient({
    log: process.env.NODE_ENV === "development" ? ["query", "error", "warn"] : ["error"]
  });

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}
`,

  "lib/auth.ts": `import { SignJWT, jwtVerify } from "jose";

const secret = () =>
  new TextEncoder().encode(process.env.AUTH_SECRET || "dev_secret_change_me");

export type AuthUser = {
  id: number;
  username: string;
  role: string;
};

export async function signToken(user: AuthUser) {
  return new SignJWT({
    id: user.id,
    username: user.username,
    role: user.role
  })
    .setProtectedHeader({ alg: "HS256" })
    .setIssuedAt()
    .setExpirationTime("8h")
    .sign(secret());
}

export async function verifyToken(token: string): Promise<AuthUser | null> {
  try {
    const { payload } = await jwtVerify(token, secret());

    return {
      id: Number(payload.id),
      username: String(payload.username),
      role: String(payload.role)
    };
  } catch {
    return null;
  }
}

export function getTokenFromRequest(req: Request) {
  const auth = req.headers.get("authorization");

  if (auth?.startsWith("Bearer ")) {
    return auth.slice(7);
  }

  const cookie = req.headers.get("cookie") || "";
  const match = cookie.match(/(?:^|; )guard_token=([^;]+)/);

  if (!match) {
    return null;
  }

  return decodeURIComponent(match[1]);
}

export async function requireAuth(req: Request) {
  const token = getTokenFromRequest(req);

  if (!token) {
    return null;
  }

  return verifyToken(token);
}
`,

  "lib/license.ts": `import crypto from "crypto";

export function generateLicenseKey() {
  const raw = crypto.randomBytes(18).toString("hex").toUpperCase();
  return [
    raw.slice(0, 6),
    raw.slice(6, 12),
    raw.slice(12, 18),
    raw.slice(18, 24),
    raw.slice(24, 30),
    raw.slice(30, 36)
  ].join("-");
}

export function getLicenseExpiry() {
  const days = Number(process.env.LICENSE_DURATION_DAYS || "365");
  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + days);
  return expiresAt;
}
`,

  "lib/paypal.ts": `type PayPalTokenResponse = {
  access_token: string;
};

function baseUrl() {
  return process.env.PAYPAL_ENV === "live"
    ? "https://api-m.paypal.com"
    : "https://api-m.sandbox.paypal.com";
}

export async function getPayPalAccessToken() {
  const clientId = process.env.PAYPAL_CLIENT_ID;
  const clientSecret = process.env.PAYPAL_CLIENT_SECRET;

  if (!clientId || !clientSecret) {
    throw new Error("Missing PayPal credentials");
  }

  const auth = Buffer.from(clientId + ":" + clientSecret).toString("base64");

  const res = await fetch(baseUrl() + "/v1/oauth2/token", {
    method: "POST",
    headers: {
      Authorization: "Basic " + auth,
      "Content-Type": "application/x-www-form-urlencoded"
    },
    body: "grant_type=client_credentials"
  });

  if (!res.ok) {
    throw new Error("Could not get PayPal access token");
  }

  const data = (await res.json()) as PayPalTokenResponse;
  return data.access_token;
}

export async function createPayPalOrder() {
  const token = await getPayPalAccessToken();
  const price = process.env.LICENSE_PRICE_USD || "49.00";

  const res = await fetch(baseUrl() + "/v2/checkout/orders", {
    method: "POST",
    headers: {
      Authorization: "Bearer " + token,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      intent: "CAPTURE",
      purchase_units: [
        {
          amount: {
            currency_code: "USD",
            value: price
          },
          description: "Universal Guard License"
        }
      ]
    })
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error("PayPal order creation failed: " + text);
  }

  return res.json();
}

export async function capturePayPalOrder(orderId: string) {
  const token = await getPayPalAccessToken();

  const res = await fetch(baseUrl() + "/v2/checkout/orders/" + orderId + "/capture", {
    method: "POST",
    headers: {
      Authorization: "Bearer " + token,
      "Content-Type": "application/json"
    }
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error("PayPal capture failed: " + text);
  }

  return res.json();
}
`,

  "middleware.ts": `import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

export function middleware(req: NextRequest) {
  const path = req.nextUrl.pathname;

  const protectedPath =
    path.startsWith("/dashboard") ||
    path.startsWith("/checkout");

  if (!protectedPath) {
    return NextResponse.next();
  }

  const token = req.cookies.get("guard_token")?.value;

  if (!token) {
    const url = req.nextUrl.clone();
    url.pathname = "/login";
    return NextResponse.redirect(url);
  }

  return NextResponse.next();
}

export const config = {
  matcher: ["/dashboard/:path*", "/checkout/:path*"]
};
`,

  "components/Nav.tsx": `"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { Shield, Users, KeyRound, CreditCard, LogOut } from "lucide-react";

export function Nav() {
  const router = useRouter();

  async function logout() {
    await fetch("/api/auth/logout", { method: "POST" });
    document.cookie = "guard_token=; path=/; max-age=0";
    router.push("/login");
  }

  return (
    <aside className="panel p-4 space-y-4">
      <div className="flex items-center gap-2 text-xl font-bold">
        <Shield className="text-blue-400" />
        Universal Guard
      </div>

      <nav className="grid gap-2 text-sm">
        <Link className="btn btn-secondary justify-start" href="/dashboard">
          <Shield size={16} /> Overview
        </Link>
        <Link className="btn btn-secondary justify-start" href="/dashboard/players">
          <Users size={16} /> Players
        </Link>
        <Link className="btn btn-secondary justify-start" href="/dashboard/licenses">
          <KeyRound size={16} /> Licenses
        </Link>
        <Link className="btn btn-secondary justify-start" href="/checkout">
          <CreditCard size={16} /> Checkout
        </Link>
        <button onClick={logout} className="btn btn-secondary justify-start">
          <LogOut size={16} /> Logout
        </button>
      </nav>
    </aside>
  );
}
`,

  "components/Shell.tsx": `import { Nav } from "./Nav";

export function Shell({ children }: { children: React.ReactNode }) {
  return (
    <main className="min-h-screen p-5 md:p-8">
      <div className="grid grid-cols-1 md:grid-cols-[260px_1fr] gap-5 max-w-7xl mx-auto">
        <Nav />
        <section>{children}</section>
      </div>
    </main>
  );
}
`,

  "app/login/page.tsx": `"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Shield } from "lucide-react";

export default function LoginPage() {
  const router = useRouter();
  const [username, setUsername] = useState("admin");
  const [password, setPassword] = useState("admin123");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    setError("");

    const res = await fetch("/api/auth/login", {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({ username, password })
    });

    const data = await res.json().catch(() => ({}));
    setLoading(false);

    if (!res.ok) {
      setError(data.error || "Login failed");
      return;
    }

    document.cookie = "guard_token=" + data.token + "; path=/; max-age=28800; SameSite=Lax";
    router.push("/dashboard");
  }

  return (
    <main className="min-h-screen grid place-items-center p-6">
      <form onSubmit={submit} className="panel w-full max-w-md p-8 space-y-5">
        <div className="flex items-center gap-3">
          <Shield className="text-blue-400" size={34} />
          <div>
            <h1 className="text-3xl font-bold">Universal Guard</h1>
            <p className="text-slate-400 text-sm">Production admin console</p>
          </div>
        </div>

        {error && (
          <div className="rounded-xl border border-red-400/30 bg-red-500/10 p-3 text-sm text-red-200">
            {error}
          </div>
        )}

        <div>
          <label className="text-sm text-slate-400">Username</label>
          <input className="input mt-1" value={username} onChange={(e) => setUsername(e.target.value)} />
        </div>

        <div>
          <label className="text-sm text-slate-400">Password</label>
          <input className="input mt-1" type="password" value={password} onChange={(e) => setPassword(e.target.value)} />
        </div>

        <button className="btn btn-primary w-full" disabled={loading}>
          {loading ? "Signing in..." : "Login"}
        </button>

        <p className="text-xs text-slate-500">
          Default credentials: admin / admin123. Change before production use.
        </p>
      </form>
    </main>
  );
}
`,

  "app/dashboard/layout.tsx": `import { Shell } from "@/components/Shell";

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return <Shell>{children}</Shell>;
}
`,

  "app/dashboard/page.tsx": `import { prisma } from "@/lib/prisma";
import { Users, KeyRound, AlertTriangle, Activity } from "lucide-react";

export default async function DashboardPage() {
  const [players, licenses, flagged, activeLicenses] = await Promise.all([
    prisma.player.count(),
    prisma.license.count(),
    prisma.player.count({ where: { status: "flagged" } }),
    prisma.license.count({ where: { status: "active" } })
  ]);

  const cards = [
    { label: "Players", value: players, icon: Users },
    { label: "Licenses", value: licenses, icon: KeyRound },
    { label: "Flagged Players", value: flagged, icon: AlertTriangle },
    { label: "Active Licenses", value: activeLicenses, icon: Activity }
  ];

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-3xl font-bold">Overview</h1>
        <p className="text-slate-400">Live platform summary.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        {cards.map((card) => {
          const Icon = card.icon;
          return (
            <div key={card.label} className="panel p-5">
              <div className="flex items-center justify-between">
                <p className="text-slate-400 text-sm">{card.label}</p>
                <Icon className="text-blue-400" size={20} />
              </div>
              <div className="text-3xl font-bold mt-3">{card.value}</div>
            </div>
          );
        })}
      </div>

      <div className="panel p-5">
        <h2 className="text-xl font-semibold mb-2">System Notes</h2>
        <ul className="list-disc pl-5 text-slate-300 space-y-1">
          <li>Authentication uses signed JWT cookies.</li>
          <li>Database access uses Prisma.</li>
          <li>PayPal checkout creates and captures orders server-side.</li>
          <li>License keys are generated after successful payment capture.</li>
        </ul>
      </div>
    </div>
  );
}
`,

  "app/dashboard/players/page.tsx": `import { prisma } from "@/lib/prisma";
import Link from "next/link";

export default async function PlayersPage() {
  const players = await prisma.player.findMany({
    orderBy: { updatedAt: "desc" }
  });

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between gap-3">
        <div>
          <h1 className="text-3xl font-bold">Players</h1>
          <p className="text-slate-400">Manage and review player accounts.</p>
        </div>
        <Link href="/dashboard/players/new" className="btn btn-primary">
          New Player
        </Link>
      </div>

      <div className="panel overflow-x-auto">
        <table className="table">
          <thead>
            <tr>
              <th>Account</th>
              <th>Character</th>
              <th>Level</th>
              <th>Gold</th>
              <th>IP</th>
              <th>Status</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {players.map((p) => (
              <tr key={p.id}>
                <td>{p.accountName}</td>
                <td>{p.characterName}</td>
                <td>{p.level}</td>
                <td>{p.gold.toString()}</td>
                <td>{p.ipAddress || "-"}</td>
                <td><span className="badge">{p.status}</span></td>
                <td>
                  <Link className="text-blue-300" href={"/dashboard/players/" + p.id}>
                    Edit
                  </Link>
                </td>
              </tr>
            ))}
            {players.length === 0 && (
              <tr>
                <td colSpan={7} className="text-slate-400">No players found.</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
`,

  "app/dashboard/players/new/page.tsx": `"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

export default function NewPlayerPage() {
  const router = useRouter();
  const [form, setForm] = useState({
    accountName: "",
    characterName: "",
    level: 1,
    gold: "0",
    ipAddress: "",
    status: "active",
    notes: ""
  });
  const [error, setError] = useState("");

  function setField(key: string, value: string | number) {
    setForm((f) => ({ ...f, [key]: value }));
  }

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    setError("");

    const res = await fetch("/api/players", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(form)
    });

    const data = await res.json().catch(() => ({}));

    if (!res.ok) {
      setError(data.error || "Could not create player");
      return;
    }

    router.push("/dashboard/players");
  }

  return (
    <form onSubmit={submit} className="panel p-5 space-y-4 max-w-2xl">
      <h1 className="text-3xl font-bold">New Player</h1>
      {error && <div className="text-red-300">{error}</div>}

      <input className="input" placeholder="Account name" value={form.accountName} onChange={(e) => setField("accountName", e.target.value)} />
      <input className="input" placeholder="Character name" value={form.characterName} onChange={(e) => setField("characterName", e.target.value)} />
      <input className="input" type="number" placeholder="Level" value={form.level} onChange={(e) => setField("level", Number(e.target.value))} />
      <input className="input" placeholder="Gold" value={form.gold} onChange={(e) => setField("gold", e.target.value)} />
      <input className="input" placeholder="IP address" value={form.ipAddress} onChange={(e) => setField("ipAddress", e.target.value)} />
      <select className="input" value={form.status} onChange={(e) => setField("status", e.target.value)}>
        <option value="active">active</option>
        <option value="flagged">flagged</option>
        <option value="banned">banned</option>
      </select>
      <textarea className="input" placeholder="Notes" value={form.notes} onChange={(e) => setField("notes", e.target.value)} />

      <button className="btn btn-primary">Create Player</button>
    </form>
  );
}
`,

  "app/dashboard/players/[id]/page.tsx": `"use client";

import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

export default function EditPlayerPage({ params }: { params: { id: string } }) {
  const router = useRouter();
  const [form, setForm] = useState<any>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    fetch("/api/players/" + params.id)
      .then((r) => r.json())
      .then((data) => setForm(data.player));
  }, [params.id]);

  function setField(key: string, value: any) {
    setForm((f: any) => ({ ...f, [key]: value }));
  }

  async function save(e: React.FormEvent) {
    e.preventDefault();
    setError("");

    const res = await fetch("/api/players/" + params.id, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(form)
    });

    const data = await res.json().catch(() => ({}));

    if (!res.ok) {
      setError(data.error || "Could not save player");
      return;
    }

    router.push("/dashboard/players");
  }

  async function remove() {
    if (!confirm("Delete this player?")) return;

    await fetch("/api/players/" + params.id, { method: "DELETE" });
    router.push("/dashboard/players");
  }

  if (!form) return <div className="panel p-5">Loading...</div>;

  return (
    <form onSubmit={save} className="panel p-5 space-y-4 max-w-2xl">
      <h1 className="text-3xl font-bold">Edit Player</h1>
      {error && <div className="text-red-300">{error}</div>}

      <input className="input" value={form.accountName} onChange={(e) => setField("accountName", e.target.value)} />
      <input className="input" value={form.characterName} onChange={(e) => setField("characterName", e.target.value)} />
      <input className="input" type="number" value={form.level} onChange={(e) => setField("level", Number(e.target.value))} />
      <input className="input" value={String(form.gold)} onChange={(e) => setField("gold", e.target.value)} />
      <input className="input" value={form.ipAddress || ""} onChange={(e) => setField("ipAddress", e.target.value)} />
      <select className="input" value={form.status} onChange={(e) => setField("status", e.target.value)}>
        <option value="active">active</option>
        <option value="flagged">flagged</option>
        <option value="banned">banned</option>
      </select>
      <textarea className="input" value={form.notes || ""} onChange={(e) => setField("notes", e.target.value)} />

      <div className="flex gap-3">
        <button className="btn btn-primary">Save</button>
        <button type="button" onClick={remove} className="btn btn-secondary">Delete</button>
      </div>
    </form>
  );
}
`,

  "app/dashboard/licenses/page.tsx": `import { prisma } from "@/lib/prisma";

export default async function LicensesPage() {
  const licenses = await prisma.license.findMany({
    orderBy: { createdAt: "desc" }
  });

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-3xl font-bold">Licenses</h1>
        <p className="text-slate-400">Issued product license keys.</p>
      </div>

      <div className="panel overflow-x-auto">
        <table className="table">
          <thead>
            <tr>
              <th>Key</th>
              <th>Email</th>
              <th>Status</th>
              <th>Order</th>
              <th>Expires</th>
            </tr>
          </thead>
          <tbody>
            {licenses.map((l) => (
              <tr key={l.id}>
                <td className="font-mono text-xs">{l.licenseKey}</td>
                <td>{l.ownerEmail || "-"}</td>
                <td><span className="badge">{l.status}</span></td>
                <td>{l.orderId || "-"}</td>
                <td>{l.expiresAt ? l.expiresAt.toISOString().slice(0, 10) : "-"}</td>
              </tr>
            ))}
            {licenses.length === 0 && (
              <tr>
                <td colSpan={5} className="text-slate-400">No licenses found.</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
`,

  "app/checkout/page.tsx": `"use client";

import { PayPalScriptProvider, PayPalButtons } from "@paypal/react-paypal-js";
import { useState } from "react";

export default function CheckoutPage() {
  const [email, setEmail] = useState("");
  const [licenseKey, setLicenseKey] = useState("");
  const [error, setError] = useState("");

  const clientId = process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID || "";

  return (
    <main className="min-h-screen grid place-items-center p-6">
      <div className="panel p-8 w-full max-w-xl space-y-5">
        <div>
          <h1 className="text-3xl font-bold">Buy Universal Guard License</h1>
          <p className="text-slate-400">Secure PayPal checkout and instant license generation.</p>
        </div>

        {error && <div className="text-red-300">{error}</div>}

        {licenseKey ? (
          <div className="rounded-2xl border border-green-400/30 bg-green-500/10 p-5">
            <p className="text-green-200 font-semibold">Payment complete. Your license key:</p>
            <p className="font-mono mt-3 break-all text-lg">{licenseKey}</p>
          </div>
        ) : (
          <>
            <input
              className="input"
              placeholder="Customer email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />

            <PayPalScriptProvider options={{ clientId, currency: "USD", intent: "capture" }}>
              <PayPalButtons
                style={{ layout: "vertical" }}
                createOrder={async () => {
                  setError("");
                  if (!email) {
                    setError("Email is required");
                    throw new Error("Email required");
                  }

                  const res = await fetch("/api/paypal/create-order", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ email })
                  });

                  const data = await res.json();

                  if (!res.ok) {
                    throw new Error(data.error || "Could not create order");
                  }

                  return data.id;
                }}
                onApprove={async (data) => {
                  const res = await fetch("/api/paypal/capture-order", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({
                      orderId: data.orderID,
                      email
                    })
                  });

                  const json = await res.json();

                  if (!res.ok) {
                    setError(json.error || "Could not capture payment");
                    return;
                  }

                  setLicenseKey(json.license.licenseKey);
                }}
              />
            </PayPalScriptProvider>
          </>
        )}
      </div>
    </main>
  );
}
`,

  "app/api/auth/login/route.ts": `import { NextResponse } from "next/server";
import bcrypt from "bcryptjs";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { signToken } from "@/lib/auth";

const schema = z.object({
  username: z.string().min(1),
  password: z.string().min(1)
});

export async function POST(req: Request) {
  const json = await req.json().catch(() => null);
  const parsed = schema.safeParse(json);

  if (!parsed.success) {
    return NextResponse.json({ error: "Invalid login payload" }, { status: 400 });
  }

  const user = await prisma.adminUser.findUnique({
    where: { username: parsed.data.username }
  });

  if (!user) {
    return NextResponse.json({ error: "Invalid credentials" }, { status: 401 });
  }

  const ok = bcrypt.compareSync(parsed.data.password, user.passwordHash);

  if (!ok) {
    return NextResponse.json({ error: "Invalid credentials" }, { status: 401 });
  }

  const token = await signToken({
    id: user.id,
    username: user.username,
    role: user.role
  });

  const res = NextResponse.json({
    token,
    user: {
      id: user.id,
      username: user.username,
      role: user.role
    }
  });

  res.cookies.set("guard_token", token, {
    httpOnly: false,
    sameSite: "lax",
    secure: process.env.NODE_ENV === "production",
    path: "/",
    maxAge: 60 * 60 * 8
  });

  return res;
}
`,

  "app/api/auth/logout/route.ts": `import { NextResponse } from "next/server";

export async function POST() {
  const res = NextResponse.json({ ok: true });
  res.cookies.set("guard_token", "", {
    path: "/",
    maxAge: 0
  });
  return res;
}
`,

  "app/api/players/route.ts": `import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requireAuth } from "@/lib/auth";

const schema = z.object({
  accountName: z.string().min(1),
  characterName: z.string().min(1),
  level: z.number().int().min(1).default(1),
  gold: z.union([z.string(), z.number()]).default("0"),
  ipAddress: z.string().optional().nullable(),
  status: z.string().default("active"),
  notes: z.string().optional().nullable()
});

export async function GET(req: Request) {
  const user = await requireAuth(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const players = await prisma.player.findMany({
    orderBy: { updatedAt: "desc" }
  });

  return NextResponse.json({ players });
}

export async function POST(req: Request) {
  const user = await requireAuth(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const json = await req.json().catch(() => null);
  const parsed = schema.safeParse(json);

  if (!parsed.success) {
    return NextResponse.json({ error: "Invalid player payload" }, { status: 400 });
  }

  const p = parsed.data;

  const player = await prisma.player.create({
    data: {
      accountName: p.accountName,
      characterName: p.characterName,
      level: p.level,
      gold: BigInt(p.gold),
      ipAddress: p.ipAddress || null,
      status: p.status,
      notes: p.notes || null
    }
  });

  await prisma.auditLog.create({
    data: {
      actor: user.username,
      action: "create",
      entity: "player",
      entityId: String(player.id),
      metadata: { accountName: player.accountName }
    }
  });

  return NextResponse.json({ player });
}
`,

  "app/api/players/[id]/route.ts": `import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requireAuth } from "@/lib/auth";

const schema = z.object({
  accountName: z.string().min(1),
  characterName: z.string().min(1),
  level: z.number().int().min(1),
  gold: z.union([z.string(), z.number()]),
  ipAddress: z.string().optional().nullable(),
  status: z.string(),
  notes: z.string().optional().nullable()
});

export async function GET(req: Request, { params }: { params: { id: string } }) {
  const user = await requireAuth(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const id = Number(params.id);

  const player = await prisma.player.findUnique({
    where: { id }
  });

  if (!player) {
    return NextResponse.json({ error: "Player not found" }, { status: 404 });
  }

  return NextResponse.json({
    player: {
      ...player,
      gold: player.gold.toString()
    }
  });
}

export async function PUT(req: Request, { params }: { params: { id: string } }) {
  const user = await requireAuth(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const id = Number(params.id);
  const json = await req.json().catch(() => null);
  const parsed = schema.safeParse(json);

  if (!parsed.success) {
    return NextResponse.json({ error: "Invalid player payload" }, { status: 400 });
  }

  const p = parsed.data;

  const player = await prisma.player.update({
    where: { id },
    data: {
      accountName: p.accountName,
      characterName: p.characterName,
      level: p.level,
      gold: BigInt(p.gold),
      ipAddress: p.ipAddress || null,
      status: p.status,
      notes: p.notes || null
    }
  });

  await prisma.auditLog.create({
    data: {
      actor: user.username,
      action: "update",
      entity: "player",
      entityId: String(player.id),
      metadata: { accountName: player.accountName }
    }
  });

  return NextResponse.json({ player });
}

export async function DELETE(req: Request, { params }: { params: { id: string } }) {
  const user = await requireAuth(req);
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const id = Number(params.id);

  await prisma.player.delete({
    where: { id }
  });

  await prisma.auditLog.create({
    data: {
      actor: user.username,
      action: "delete",
      entity: "player",
      entityId: String(id)
    }
  });

  return NextResponse.json({ ok: true });
}
`,

  "app/api/licenses/verify/route.ts": `import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";

const schema = z.object({
  licenseKey: z.string().min(1)
});

export async function POST(req: Request) {
  const json = await req.json().catch(() => null);
  const parsed = schema.safeParse(json);

  if (!parsed.success) {
    return NextResponse.json({ valid: false, error: "Invalid payload" }, { status: 400 });
  }

  const license = await prisma.license.findUnique({
    where: { licenseKey: parsed.data.licenseKey }
  });

  if (!license) {
    return NextResponse.json({ valid: false, reason: "not_found" });
  }

  if (license.status !== "active") {
    return NextResponse.json({ valid: false, reason: "inactive" });
  }

  if (license.expiresAt && license.expiresAt < new Date()) {
    return NextResponse.json({ valid: false, reason: "expired" });
  }

  return NextResponse.json({
    valid: true,
    license: {
      productId: license.productId,
      ownerEmail: license.ownerEmail,
      expiresAt: license.expiresAt
    }
  });
}
`,

  "app/api/paypal/create-order/route.ts": `import { NextResponse } from "next/server";
import { z } from "zod";
import { createPayPalOrder } from "@/lib/paypal";

const schema = z.object({
  email: z.string().email()
});

export async function POST(req: Request) {
  const json = await req.json().catch(() => null);
  const parsed = schema.safeParse(json);

  if (!parsed.success) {
    return NextResponse.json({ error: "Valid email is required" }, { status: 400 });
  }

  try {
    const order = await createPayPalOrder();
    return NextResponse.json(order);
  } catch (e) {
    return NextResponse.json(
      { error: e instanceof Error ? e.message : "Could not create order" },
      { status: 500 }
    );
  }
}
`,

  "app/api/paypal/capture-order/route.ts": `import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { capturePayPalOrder } from "@/lib/paypal";
import { generateLicenseKey, getLicenseExpiry } from "@/lib/license";

const schema = z.object({
  orderId: z.string().min(1),
  email: z.string().email()
});

export async function POST(req: Request) {
  const json = await req.json().catch(() => null);
  const parsed = schema.safeParse(json);

  if (!parsed.success) {
    return NextResponse.json({ error: "Invalid capture payload" }, { status: 400 });
  }

  const { orderId, email } = parsed.data;

  try {
    const capture = await capturePayPalOrder(orderId);

    const status = String(capture.status || "");

    if (status !== "COMPLETED") {
      return NextResponse.json({ error: "Payment not completed", status }, { status: 400 });
    }

    const payerId = capture.payer?.payer_id || null;

    const existing = await prisma.license.findUnique({
      where: { orderId }
    });

    if (existing) {
      return NextResponse.json({ license: existing });
    }

    const license = await prisma.license.create({
      data: {
        productId: process.env.LICENSE_PRODUCT_ID || "UG-PROD-001",
        licenseKey: generateLicenseKey(),
        ownerEmail: email,
        status: "active",
        activatedAt: new Date(),
        expiresAt: getLicenseExpiry(),
        orderId,
        payerId
      }
    });

    await prisma.auditLog.create({
      data: {
        actor: email,
        action: "paypal_capture",
        entity: "license",
        entityId: String(license.id),
        metadata: { orderId, payerId }
      }
    });

    return NextResponse.json({ license });
  } catch (e) {
    return NextResponse.json(
      { error: e instanceof Error ? e.message : "Could not capture payment" },
      { status: 500 }
    );
  }
}
`,

  "app/api/paypal/webhook/route.ts": `import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function POST(req: Request) {
  const body = await req.json().catch(() => null);

  if (!body) {
    return NextResponse.json({ error: "Invalid webhook body" }, { status: 400 });
  }

  await prisma.auditLog.create({
    data: {
      actor: "paypal",
      action: String(body.event_type || "webhook"),
      entity: "paypal",
      entityId: String(body.id || ""),
      metadata: body
    }
  });

  return NextResponse.json({ received: true });
}
`
};

for (const [rel, content] of Object.entries(files)) {
  write(rel, content);
}

console.log("");
console.log("Created project:");
console.log(root);
console.log("");
console.log("Next steps:");
console.log('1) cd "' + root + '"');
console.log("2) npm install");
console.log("3) copy .env.example .env.local");
console.log("4) Edit .env.local with your PostgreSQL and PayPal values");
console.log("5) npx prisma db push");
console.log("6) npm run db:seed");
console.log("7) npm run dev");
console.log("");
console.log("Default login:");
console.log("username: admin");
console.log("password: admin123");
console.log("");
